version: '3.7'

services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 5000:5000

  docker-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myserver'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  # my-redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
